[package]
name = "my_rust"
author = "Nestor Wheelock"
license = "GNU GPLv3"
description ="My rust manager.  usage: my_rust --list, --details"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5"
ctrlc = "3.2"
dirs = "4.0"
clap = { version = "4.0", features = ["derive"] }
